//*****LOGIN, REGISTER, ADD, DELETE *****/
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHILD_LOGIN_START = 'CHILD_LOGIN_START';
export const CHILD_LOGIN_SUCCESS = 'CHILD_LOGIN_SUCCESS';
export const CHILD_LOGIN_ERROR = 'CHILD_LOGIN_ERROR';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const ADD_CHILD_START = 'ADD_CHILD_START';
export const ADD_CHILD_SUCCESS = 'ADD_CHILD_SUCCESS';
export const ADD_CHILD_ERROR = 'ADD_CHILD_ERROR';

export const DELETE_CHILD_START = 'DELETE_CHILD_START';
export const DELETE_CHILD_SUCCESS = 'DELETE_CHILD_SUCCESS';
export const DELETE_CHILD_ERROR = 'DELETE_CHILD_ERROR';

//*****CHORES *****/
export const FETCH_CHORES_START = 'FETCH_CHORES_START';
export const FETCH_CHORES_SUCCESS = 'FETCH_CHORES_SUCCESS';
export const FETCH_CHORES_ERROR = 'FETCH_CHORES_ERROR';

//https://chore-tracker1.herokuapp.com
